// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrganizingFinances.Context;

#nullable disable

namespace OrganizingFinances.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230909132309_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrganizingFinances.Entities.RegistroDivida", b =>
                {
                    b.Property<Guid>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataDeVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("TituloRegistro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ValorRegistro")
                        .HasColumnType("double precision");

                    b.HasKey("IdRegistro");

                    b.ToTable("registroDividas");
                });
#pragma warning restore 612, 618
        }
    }
}
